#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Installing ROMarrNG source files..."
ynh_setup_source --dest_dir="$install_dir" --source_id="main"
chown -R "$app:$app" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Preparing ROMarrNG's settings, plugins, and default library..."

romarrng_prepare_data
romarrng_install_python_dependencies

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Configuring the localhost service and Nginx reverse proxy..."
romarrng_prepare_service
romarrng_register_service

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting ROMarrNG..."
romarrng_start_service

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
