#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing ROMarrNG's YunoHost service, logs, and reverse proxy..."
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
	yunohost service remove "$app"
fi
ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_config_remove_logrotate
rm -rf -- "/opt/yunohost/$app/uv" "/opt/yunohost/$app/uv-python"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
