#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping ROMarrNG..."
ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading ROMarrNG source files..."
ynh_setup_source --dest_dir="$install_dir" --source_id="main" --full_replace
chown -R "$app:$app" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
romarrng_prepare_data
romarrng_install_python_dependencies
romarrng_prepare_service
romarrng_register_service

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting ROMarrNG..."
romarrng_start_service

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
