#!/bin/bash

source _common.sh

ynh_script_progression "Stopping ROMarrNG..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Installing the pinned ROMarrNG release..."
ynh_setup_source --dest_dir="$install_dir" --source_id="main" --full_replace=1
chown -R "$app:$app" "$install_dir"
romarrng_prepare_data
romarrng_install_python_dependencies

ynh_script_progression "Refreshing the service and reverse proxy..."
romarrng_prepare_service

ynh_script_progression "Starting ROMarrNG..."
romarrng_start_service
romarrng_register_service

ynh_script_progression "ROMarrNG upgrade completed"
